name: my first job

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: script
          run: | 
            echo "my first actions"
            ls -lrta
            cat README.md
        - name: generate ascii adworks 
          run: |
            apt install cowsay -y
            cowsay -f dragon "Run for cover im coming" > dragon.txt

       

