name: multiple jobs

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
        - name: checkout action 
          uses: actions/checkout@v4

        - name: run script
          run: | 
            chmod +x ascii.sh
            ./ascii.sh            

